In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import random
import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [8]:
# train_data 확인 2022-01-01 ~ 2023-04-04
data = pd.read_csv('drive/MyDrive/LG AIMERS/최연아/open/train.csv')

In [10]:
# '2022-04-25' 열의 인덱스를 찾기
column_to_stop = "2022-04-25"
stop_index = data.columns.get_loc(column_to_stop)

# '2022-04-25' 열까지만 유지하고 나머지를 제거하기
data = data.iloc[:, :stop_index + 1]
data.head()

,브랜드,2022-01-01,2022-01-02,2022-01-03,2022-01-04,2022-01-05,2022-01-06,2022-01-07,2022-01-08,2022-01-09,...,2022-04-16,2022-04-17,2022-04-18,2022-04-19,2022-04-20,2022-04-21,2022-04-22,2022-04-23,2022-04-24,2022-04-25
0,B002-00001,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,1
1,B002-00002,0,0,0,0,0,0,0,0,0,...,5,5,5,5,5,5,7,7,4,4
2,B002-00002,0,0,0,0,0,0,0,0,0,...,3,3,3,3,3,2,1,1,2,2
3,B002-00002,0,0,0,0,0,0,0,0,0,...,5,4,4,3,3,3,3,3,4,4
4,B002-00003,0,0,0,0,0,0,0,0,0,...,30,21,21,13,12,1,5,5,9,9

In [12]:
# '2022-04-05' 열의 위치 찾기
column_index = data.columns.get_loc('2022-04-05')

# '2022-04-25' 열과 그 이후의 모든 열 선택
data = data.iloc[:, column_index:]

# 결과 확인
data.head()

,2022-04-05,2022-04-06,2022-04-07,2022-04-08,2022-04-09,2022-04-10,2022-04-11,2022-04-12,2022-04-13,2022-04-14,...,2022-04-16,2022-04-17,2022-04-18,2022-04-19,2022-04-20,2022-04-21,2022-04-22,2022-04-23,2022-04-24,2022-04-25
0,1,0,0,0,0,0,0,0,2,2,...,1,0,0,0,0,0,0,0,1,1
1,3,2,5,7,6,7,6,5,3,4,...,5,5,5,5,5,5,7,7,4,4
2,2,1,1,2,33,33,37,39,10,5,...,3,3,3,3,3,2,1,1,2,2
3,4,5,5,6,75,75,78,79,12,7,...,5,4,4,3,3,3,3,3,4,4
4,1,1,2,2,2,0,0,0,0,3,...,30,21,21,13,12,1,5,5,9,9

In [13]:
data.to_csv('submit3.csv', index=False)